spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev #开发环境
  application:
    name: springcloud_config_shnma_dev

---

spring:
  profiles: test #测试环境
  application:
    name: springcloud_config_shnma_test
